### ISSUE TITLE
Grafana stops drawing some pings after a few minutes

### ISSUE THREAD

**Issue by Iv4nd1** [WoLpH/fping-exporter#1]
Hello,

I'm fairly new to Grafana so I'm trying to see what's wrong with my current setup.

Issue : No graphs when having more than 2 hosts to ping for the 3+ hosts that are configured.

Step to reproduce : Setup 2 pings like the two IP for Google DNS for example and then setup a third ping towards a third party IP.

Result : The Google DNS pings are working fine but the third ping drawing stops after a few minutes.

Expected result : all graphs should be displayed.

System information : 
Debian 11 with Prometheus 2.24.1 and Grafana 9.0.2 (without Docker)

Thanks

**Comment by wolph** [comment]
It would be good to see the log from the exporter. It should show why it's not working anymore.

Some devices actually block pinging after a little while so that could be an issue here. In that case you will need to decrease the ping interval. The `period` is set to `1000ms` by default, but you can safely increase it if needed:
```
[host:router]
address = 192.168.0.1
period = 5000
```

**Comment by Iv4nd1** [comment]
Hello,
I have changed to period timer according to your advice.
I have upgraded my Node/NPM version on my Debian 11 machine
And I have enabled the lingering mode with loginctl for the user account that is running pm2.

So far, it seems to work but I have this error in the exporter logs : 
```
AssertionError: No match for '[1657719451.22752] 192.168.1.1 : [160], timed out (9.76 avg, 0% loss)'

Traceback (most recent call last):
  File "/opt/tools/fping-exporter/fping_exporter.py", line 133, in run
    await self.run_process(args)
  File "/opt/tools/fping-exporter/fping_exporter.py", line 87, in run_process
    assert match, 'No match for %r' % line
```

Thank you.

**Comment by wolph** [comment]
It seems that's a bug in the script, it's not handling the `timed out` correctly. That's just a result though, the device you're trying to reach is giving a timeout so I'm guessing it's blocking the ping (after a while?).

You can try it yourself to see what output you're getting:
```
fping --period=1000 --loop 192.168.1.1
```

**Comment by wolph** [comment]
I've created a new version that solves the `timed out` bug, but the bigger issue is that the device you're pinging is giving timeouts.

It's possible that the latency for that device is too high, in which case you need to increase the `timeout` parameter (`fping` defaults to 500ms, you can try `1000` for `1000ms`).

Looking at the output slightly more carefully I think it is probably packet loss. The first 159 packets succeeded with an average latency of 9.76ms. And the 160th packet gets a timeout. In any case, please try the newer version, it should at least keep going for you.

If it quickly restores than it's most likely just a packet loss issue.
If it stays down after that 160th packet each time, than it's probably a firewall that's blocking the ping

**Comment by Iv4nd1** [comment]
Hello,
Your advice did work great !
I have changed the period parameter and I have updated my VM with your new python script.
Everything works fine now.
I think you were right about the destination doing some rate limiting.
Cheers.
